(include_subdirs unqualified)

(library
 (name STLC)
 (modules
  impl
  spec
  type
  test
  baseType
  baseType_Staged_C
  display)
  (libraries qcheck crowbar fast_gen util core core_unix ppx_staged ppxlib)
  (preprocess
    (pps ppx_jane ppx_staged ppxlib.metaquot)))

(env
 (dev
  (flags
   (:standard -g -w "-26-27-32-33-34-37-39-6"))))