(include_subdirs unqualified)

(library
 (name BST)
 (modules
  impl
  spec
  type
  test
  baseType
  baseTypCsr
  baseTypGsr
  baseBespoke
  baseSingleBespoke
  baseTypeC
  nat
  display)
 (libraries qcheck crowbar fast_gen util core core_unix ppx_staged)
 (preprocess
  (pps ppx_jane ppx_staged)))

(env
 (dev
  (flags
   (:standard -g -w "-26-27-32-33-34-37-39"))))